version: '3'

services:
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    command: ["sh", "-c", "node server.js & cd fastapi && uvicorn main:app --host 0.0.0.0 --port 9000"]
    environment:
      - OPENAI_API_KEY=your_openai_api_key
